[error] sbt.librarymanagement.ResolveException: Error downloading ml.dmlc:xgboost4j_2.11:latest_version_num
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\Matheus\.ivy2\localml.dmlc\xgboost4j_2.11\latest_version_num\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/ml/dmlc/xgboost4j_2.11/latest_version_num/xgboost4j_2.11-latest_version_num.pom
[error]   not found: https://repository.apache.org/snapshots/ml/dmlc/xgboost4j_2.11/latest_version_num/xgboost4j_2.11-latest_version_num.pom
[error]   not found: https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/ml/dmlc/xgboost4j_2.11/latest_version_num/xgboost4j_2.11-latest_version_num.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3486)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading ml.dmlc:xgboost4j_2.11:latest_version_num
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\Matheus\.ivy2\localml.dmlc\xgboost4j_2.11\latest_version_num\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/ml/dmlc/xgboost4j_2.11/latest_version_num/xgboost4j_2.11-latest_version_num.pom
[error]   not found: https://repository.apache.org/snapshots/ml/dmlc/xgboost4j_2.11/latest_version_num/xgboost4j_2.11-latest_version_num.pom
[error]   not found: https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/ml/dmlc/xgboost4j_2.11/latest_version_num/xgboost4j_2.11-latest_version_num.pom
